services:
  backend:
    build:
      context: ./backend
    # We define volumes for persistence in both modes
    volumes:
      - ./backend/shows:/app/shows
      - ./backend/db.json:/app/db.json

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend